import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const session = useSession();
  const user = session.data?.user;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {user ? (
          <div>
            <h1>{user.name}</h1>
          </div>
        ) : (
          <div>
            <h1>Not signed in</h1>
            <h1>
              Login <a href="/api/auth/signin">here</a>
              Ezt még mantineosítani kell
            </h1>
          </div>
        )}
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
